repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.5
  hooks:
    # Run the linter (--fix requires check before format)
    - id: ruff-check
      args: [ --fix ]
      files: 'src/.*|tests/.*'
    # Run the formatter
    - id: ruff-format
      files: 'src/.*|tests/.*'
